                      linear regression fitting a **line**

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np

In [ ]:
#data_url = "http://lib.stat.cmu.edu/datasets/boston"
#raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
#data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
#target = raw_df.values[1::2, 2]


In [ ]:
housing = fetch_california_housing()
features = housing.data[:,0:2]
target=housing.target

In [ ]:
regression=LinearRegression()
regression

LinearRegression()

In [ ]:
model=regression.fit(features,target)
model

LinearRegression()

In [ ]:
model.intercept_ #And β1 and β2 are shown using coef_

-0.1018903275908265

In [ ]:
target[0]*1000

4526.0

In [ ]:
model.predict(features)[0]*1000

4207.126263821179

In [ ]:
model.coef_ 

array([0.43169191, 0.01744134])

              handeling interactive effects

              using polynomial features *****

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
housing = fetch_california_housing()
features=housing.data[:,0:2]
target=housing.target

In [ ]:
interaction=PolynomialFeatures(degree=3,include_bias=False, interaction_only=True)
features_interaction=interaction.fit_transform(features)


In [ ]:
regression=LinearRegression()


In [ ]:
model=regression.fit(features_interaction,target)

   FORMULA

In [ ]:
features_interaction[0]

array([  8.3252,  41.    , 341.3332])

In [ ]:
features[0]

array([ 8.3252, 41.    ])

In [ ]:
interaction_term=np.multiply(features[:,0],features[:,1])

In [ ]:
interaction_term[0]

341.33320000000003

        FITTING A NON LINEAR REALATIONSHOIP

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
housing = fetch_california_housing()
features=housing.data[:,0:2]
target=housing.target

In [ ]:
polynomial=PolynomialFeatures(degree=3,include_bias=False)
features_polynomial=polynomial.fit_transform(features)


In [ ]:
regression=LinearRegression()

In [ ]:
model=regression.fit(features_polynomial, target)

In [ ]:
features[0]

array([ 8.3252, 41.    ])

In [ ]:
features[0]**2

array([  69.30895504, 1681.        ])

In [ ]:
features[0]**3

array([  577.0109125, 68921.       ])

In [ ]:
features_polynomial[0]

array([8.32520000e+00, 4.10000000e+01, 6.93089550e+01, 3.41333200e+02,
       1.68100000e+03, 5.77010912e+02, 2.84166716e+03, 1.39946612e+04,
       6.89210000e+04])

                REDUSING variance through regulariation 

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler


In [ ]:
housing = fetch_california_housing()
features=housing.data
target=housing.target

In [ ]:
scaler=StandardScaler()
features_standardized = scaler.fit_transform(features)

In [ ]:
regression= Ridge(alpha=0.5)

In [ ]:
model=regression.fit(features_standardized,target)

In [ ]:
model

Ridge(alpha=0.5)

In [ ]:
from sklearn.linear_model import RidgeCV

In [ ]:
regr_cv=RidgeCV(alphas=[0.1,1.0,10.0])

In [ ]:
model_cv=regr_cv.fit(features_standardized,target)

In [ ]:
model_cv.coef_

array([ 0.8293461 ,  0.11939823, -0.26422311,  0.30398067, -0.00427544,
       -0.03936068, -0.8937389 , -0.86433656])

In [ ]:
model_cv.alpha_

10.0

In [3]:
!pip install lasso

  Created wheel for lasso: filename=lasso-0.0.5-py3-none-any.whl size=4813 sha256=051bc97f096a73b6f5e5686f018ce41e2fcf02949b0223e38c0d705cecc7a99a
  Stored in directory: /root/.cache/pip/wheels/a9/61/c3/205a56dbd39796ab76d37c25928477011850c05b5cfa0bbb4f
  Created wheel for delorean: filename=Delorean-1.0.0-py3-none-any.whl size=9599 sha256=dbbc492c177a4b4fa0fd1a15f603abdd05f1fcf5f94906850df69a113d1307d0
  Stored in directory: /root/.cache/pip/wheels/2c/74/9f/ee1a620f88655064739468477eed3a3e97b6e0090f87b79db1
  Created wheel for schema: filename=schema-0.3.1-py3-none-any.whl size=7087 sha256=73a7a86ef09de860d2e779aae8df48e8243244662c2e7931f37d9419a7c5810f
  Stored in directory: /root/.cache/pip/wheels/95/19/8c/3e92f744853670e0d1e2d1160aa6d8f68b1ba957efa5595446
Successfully built lasso delorean schema


In [6]:
from sklearn.linear_model import Lasso
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

In [14]:
housing = fetch_california_housing()
features = housing.data
target=housing.target

In [15]:
scaler=StandardScaler()
features_standardized=scaler.fit_transform(features)

In [16]:
regression=Lasso(alpha=0.5)

In [20]:
model=regression.fit(features_standardized,target)
model

Lasso(alpha=0.5)

In [19]:
model.coef_

array([ 0.29398939,  0.        ,  0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        ])