TRAING A BINARY CALSSIFIER    formulas >>>>>in  memo note 

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [2]:
iris = datasets.load_iris()
features=iris.data[:100,:]
target=iris.target[:100]

In [3]:
scaler= StandardScaler()
features_standerdized=scaler.fit_transform(features) 

In [4]:
logistic_regression=LogisticRegression(random_state=0)

In [5]:
model=logistic_regression.fit(features_standerdized,target)

In [6]:
new_observation=[[.5,.5,.5,.5]]

In [7]:
model.predict(new_observation)

array([1])

In [8]:
model.predict_proba(new_observation)

array([[0.17738424, 0.82261576]])

                  TRAINING MULTICLASS CALSSIFIER formula in>>> memo note  

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [10]:
iris=datasets.load_iris()
features=iris.data
target=iris.target

In [11]:
scaler=StandardScaler()
features_standerdized=scaler.fit_transform(features)


In [12]:
logistic_regression=LogisticRegression(random_state=0,multi_class='multinomial')


In [13]:
model=logistic_regression.fit(features_standerdized,target)

In [14]:
new_observation=[[.5,.5,.5,.5]]

In [15]:
model.predict(new_observation)

array([1])

Explanation - (MLR)
image.png

In [16]:
model.predict_proba(new_observation)

array([[0.01982185, 0.74491886, 0.23525928]])

In [17]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [18]:
iris= datasets.load_iris()
features=iris.data
target=iris.target


In [25]:
scaler=StandardScaler()
features_standardized=scaler.fit_transform(features)

In [31]:
logistic_regression=LogisticRegressionCV(penalty='l2',Cs=10, random_state=0, n_jobs=-1)

In [32]:
model = logistic_regression.fit(features_standardized,target)

In [33]:
model

LogisticRegressionCV(n_jobs=-1, random_state=0)

                   TRAINNG A CLASSIFIER ON VERY LARDE DATA
                   

In [35]:

from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [37]:
iris=datasets.load_iris()
features=iris.data
target=iris.target

In [38]:
scaler=StandardScaler()
features_standardized=scaler.fit_transform(features)

In [40]:
logistic_regression.fit(features_standerdized,target)

LogisticRegressionCV(n_jobs=-1, random_state=0)

In [41]:
model=logistic_regression.fit(features,target)